spring:
 jpa:
  hibernate.ddl-auto: update
  show-sql: false
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect
    jdbc:
     batch_size: 50
          
 datasource:
  url: jdbc:mysql://localhost/bd?createDatabaseIfNotExist=true&serverTimezone=UTC
  username: root
  password: root

app:
  domain-front: http://localhost:4200
  
#Configuración del servidor (contexto, https, página de error)
server:
  port: 8080
  servlet:
    context-path: /prueba