#Producción 
spring:
 jpa:
  hibernate.ddl-auto: update
  show-sql: false
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQL5Dialect
    jdbc:
     batch_size: 50
          
 datasource:
  url: jdbc:mysql://localhost/bd?createDatabaseIfNotExist=true&serverTimezone=UTC
  username: root
  password: root

app:
  local-domain-front: http://localhost:4200
  remote-domain-front: https://angular-architecture.herokuapp.com/
  
#Configuración del servidor (contexto, https, página de error)
server:
  port: ${PORT:8080}
  
  
---     
#Desarrollo
spring:  
  config:
    activate:
      on-profile:
      - development
  datasource:
    url: jdbc:mysql://localhost/bd?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root